locomotion_task:
    initial_base_lin: [0., 0., 0.766, 0., 0., 0.]
    initial_base_ang: [0., 0., 0., 0., 0., 0.]

    # Left Foot: 0, Right Foot: 1
    initial_ee_motion_lin:
        0: [0.003, -0.111, 0.]
        1: [0.003, 0.111, 0.]
    initial_ee_motion_ang:
        0: [0., 0., 0.]
        1: [0., 0., 0.]
    ee_phase_durations:
        0: [0.45, 0.75, 1.65, 0.75, 0.45]
        1: [1.65, 0.75, 1.65]
    ee_in_contact_at_start:
        0: True
        1: True

    final_base_lin: [0.3, 0.0, 0.766, 0., 0., 0.]
    final_base_ang: [0., 0., 0., 0., 0., 0.]

    terrain_type: "flat_ground"

    robot_name: "atlas"
