locomotion_task:

    initial_base_lin: [0., 0., 0.766, 0., 0., 0.]
    initial_base_ang: [0., 0., 0., 0., 0., 0.]

    # Left Foot: 0, Right Foot: 1
    initial_ee_motion_lin:
        0: [0.003, -0.111, 0.]
        1: [0.003, 0.111, 0.]
    initial_ee_motion_ang:
        0: [0., 0., 0.]
        1: [0., 0., 0.]

    final_base_lin: [0.3, 0.0, 0.766, 0., 0., 0.]
    final_base_ang: [0., 0., 0., 0., 0., 0.]

    terrain_type: "flat_ground"

locomotion_param:

    duration_base_polynomial: 0.1
    force_polynomials_per_stance_phase: 3
    ee_polynomials_per_swing_phase: 2
    force_limit_in_normal_direction: 1000.
    dt_constraint_range_of_motion: 0.08
    dt_constraint_dynamic: 0.1
    dt_constraint_base_motion: 0.025
    bound_phase_duration: [0.2, 2.0]

    ee_phase_durations:
        0: [0.45, 0.75, 1.65, 0.75, 0.45]
        1: [1.65, 0.75, 1.65]
    ee_in_contact_at_start:
        0: True
        1: True

