locomotion_task:
    initial_base_lin: [0., 0., 0.766, 0., 0., 0.]
    initial_base_ang: [0., 0., 0., 0., 0., 0.]

    # Left: 0, Right: 1
    initial_ee_motion_lin:
        left: [0.003, -0.111, 0.]
        right: [0.003, 0.111, 0.]
    initial_ee_motion_ang:
        left: [0., 0., 0.]
        right: [0., 0., 0.]
    ee_phase_durations:
        left: [0.45, 0.75, 1.65, 0.75, 0.45]
        right: [1.65, 0.75, 1.65]
    ee_in_contact_at_start:
        left: True
        right: True

    final_base_lin: [0.3, 0.0, 0.766, 0., 0., 0.]
    final_base_ang: [0., 0., 0., 0., 0., 0.]

    terrain_type: "flat_ground"

    robot_name: "atlas"
